---

- hosts: all
  gather_facts: no

  tasks:
    - name: run show command
      ios_command:
        commands:
          - "{{ show_command }}"
      register: result

    - name: debug
      debug:
        msg: "{{ result.stdout_lines[0] }}"
